import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/app/globals.css';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import "@/app/globals.css";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* 🔹 Add this header block */}
        <header className="flex items-center justify-between px-6 py-4 bg-white shadow-soft">
          <h1 className="text-lg font-semibold">Golf Stat App</h1>

          <nav className="flex gap-6 text-sm">
            <Link href="/dashboard">Dashboard</Link>
            <Link href="/add-round" className="font-medium text-brand">
              + Add Round
            </Link>
            <Link href="/rounds">Rounds</Link>
          </nav>
        </header>

        {/* page content */}
        <main>{children}</main>
      </body>
    </html>
  );
}